[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow = "E1pwRt14gFtx1LyjiNDtmaVc6FaFfJ5CdfUMTJcuNw8w"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run jest --preset ts-jest"
